name: Test gig-map

on: [push, pull_request]  

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
      NXF_VER: "21.10.6"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: set up Python3
        uses: actions/setup-python@v3
      
      - name: Install BASH Workbench
        run: pip3 install git+https://github.com/FredHutch/bash-workbench.git
      
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h

      - name: Configure gig-map repository
        run: |
          wb link_local_repo --path $PWD --name gig-map

      - name: Download bash-workbench-tools
        run: |
          wb add_repo --remote-name FredHutch/bash-workbench-tools

      - name: Download genomes
        run: |
          mkdir test_data/download_genomes
          cd test_data/download_genomes
          
          # Specify the tool and launcher to use
          wb setup_dataset \
            --tool gig-map/download_genomes \
            --launcher FredHutch_bash-workbench-tools/nextflow_docker
          
          # Specify which table of genomes to download
          wb set_tool_params --genome_csv ../Escherichia_virus_T4.csv

          # Set the params for the nextflow docker launcher (there are none)
          wb set_launcher_params

          # Run the dataset and wait until it finishes
          wb run_dataset --wait

          # Make sure that the genomes were downloaded
          (( $(ls genomes/*.fasta.gz | wc -l) == 6 ))
      
      - name: Download genes
        run: |
          mkdir test_data/download_genes
          cd test_data/download_genes
          
          # Specify the tool and launcher to use
          wb setup_dataset \
            --tool gig-map/download_genes \
            --launcher FredHutch_bash-workbench-tools/nextflow_docker
          
          # Specify which table of genes to download
          wb set_tool_params --genome_csv ../Escherichia_virus_T4.csv

          # Set the params for the nextflow docker launcher (there are none)
          wb set_launcher_params

          # Run the dataset and wait until it finishes
          wb run_dataset --wait

          # Make sure that the genes were downloaded
          (( $(ls genes/*.fasta.gz | wc -l) == 6 ))
