name: Test gig-map

on: [push, pull_request]  

jobs:

  test:
    runs-on: ubuntu-latest
    env:
      NXF_ANSI_LOG: 0
    steps:
      - uses: actions/checkout@v1
      - name: Install Nextflow
        run: |
          wget -qO- get.nextflow.io | bash
          sudo mv nextflow /usr/local/bin/
      - name: Free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
      - name:  DIAMOND alignment from FASTA
        run: |
          NXF_VER=21.04.1 nextflow run main.nf -c nextflow.config -profile testing -w work/ -with-docker ubuntu:latest --genome_tables test_data/NCBI_Escherichia_coli_genomes.test_subset.csv --genes_fasta test_data/GCA_000005845.2_ASM584v2_protein.faa.gz --output_folder output_diamond_fasta --output_prefix output -resume

      - name:  DIAMOND alignment from DMND
        run: |
          NXF_VER=21.04.1 nextflow run main.nf -c nextflow.config -profile testing -w work/ -with-docker ubuntu:latest --genome_tables test_data/NCBI_Escherichia_coli_genomes.test_subset.csv --genes_dmnd test_data/GCA_000005845.2_ASM584v2_protein.dmnd --output_folder output_diamond_dmnd --output_prefix output -resume

      - name:  BLAST alignment from FASTA
        run: |
          NXF_VER=21.04.1 nextflow run main.nf -c nextflow.config -profile testing -w work/ -with-docker ubuntu:latest --genome_tables test_data/NCBI_Escherichia_coli_genomes.test_subset.csv --genes_fasta test_data/GCA_000005845.2_ASM584v2_protein.faa.gz --output_folder output_blast_fasta --output_prefix output --aligner blast -resume

      - name:  Import previous distances
        run: |
          NXF_VER=21.04.1 nextflow run main.nf -c nextflow.config -profile testing -w work/ -with-docker ubuntu:latest --genome_tables test_data/NCBI_Escherichia_coli_genomes.test_subset.csv --genes_fasta test_data/GCA_000005845.2_ASM584v2_protein.faa.gz --output_folder output_blast_fasta --output_prefix output --genome_distances output_diamond_fasta/distances.csv.gz -resume
